<?php


namespace App\Services;

use App\Repositories\EmailMessageRepositoryInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class EmailMessageService extends BaseRepositoryService implements EmailMessageServiceInterface
{
    public function __construct(EmailMessageRepositoryInterface $repository)
    {
        parent::__construct($repository);
    }

    public function reformatInputs(array $inputArray): array
    {
        $inputArray['user_id'] = Auth::user()->getAuthIdentifier();
        $inputArray['address'] = $inputArray['address'] ?? config('mail.from.address');
        $inputArray['name'] = $inputArray['name'] ?? config('mail.from.name');
        foreach ($inputArray['recipients'] as $key => &$value){
            if(!isset($value['name'])){
                $value['name'] = explode("@",  $value['address'])[0];
            }
        }
        return $inputArray;
    }

    public function makeItem(array $inputs): ?Model
    {
        return parent::makeItem($this->reformatInputs($inputs)); // TODO: Change the autogenerated stub
    }

    public function editItem($id, array $inputs): ?Model
    {
        return parent::editItem($id, $this->reformatInputs($inputs));
    }
}